[workspace]
resolver = "2"
members = ["crates/bin/serve", "crates/lib/web_runner","crates/lib/webcomponents"]

[profile.dev]
debug = false       # this has been turned off to improve compilation performance. Re-enable this for debug symbols, for instance for stack traces, disabled for shorting build duration, increases build duration when enabled
